name: Rust

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Add components
        run: rustup component add clippy rustfmt

      - name: Rustfmt
        run: |
          cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings
      
      - name: Build
        run: cargo build --all-features --verbose

      - name: Test
        run: cargo test --all-features --verbose
